// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MinuteClinic.Models;

#nullable disable

namespace MinuteClinic.Migrations
{
    [DbContext(typeof(MinuteClinicContext))]
    [Migration("20241021055302_SeedProviderData")]
    partial class SeedProviderData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MinuteClinic.Models.Clinics", b =>
                {
                    b.Property<int>("ClinicId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ClinicId"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ClinicName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<int>("ZipCode")
                        .HasColumnType("int");

                    b.HasKey("ClinicId");

                    b.ToTable("Clinics", (string)null);

                    b.HasData(
                        new
                        {
                            ClinicId = 1,
                            City = "Anytown",
                            ClinicName = "NY Clinic",
                            Location = "1234 Elm St",
                            State = "NY",
                            ZipCode = 12345
                        },
                        new
                        {
                            ClinicId = 2,
                            City = "Othertown",
                            ClinicName = "IL Clinic",
                            Location = "5678 Oak St",
                            State = "IL",
                            ZipCode = 45678
                        },
                        new
                        {
                            ClinicId = 3,
                            City = "Thirdtown",
                            ClinicName = "MI Clinic",
                            Location = "91011 Pine St",
                            State = "MI",
                            ZipCode = 90012
                        });
                });

            modelBuilder.Entity("MinuteClinic.Models.Provider", b =>
                {
                    b.Property<int>("ProviderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProviderId"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ProviderId");

                    b.ToTable("Provider", (string)null);

                    b.HasData(
                        new
                        {
                            ProviderId = 1,
                            Address = "NY",
                            Name = "Moderna"
                        },
                        new
                        {
                            ProviderId = 2,
                            Address = "PL",
                            Name = "AstraZeneca"
                        },
                        new
                        {
                            ProviderId = 3,
                            Address = "IL",
                            Name = "Pfizer"
                        });
                });

            modelBuilder.Entity("MinuteClinic.Models.Vaccine", b =>
                {
                    b.Property<int>("VaccineId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VaccineId"));

                    b.Property<string>("AvailableTimeSlots")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ClinicId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("ProviderId")
                        .HasColumnType("int");

                    b.Property<string>("VaccineImage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("VaccineId");

                    b.HasIndex("ClinicId");

                    b.HasIndex("ProviderId");

                    b.ToTable("Vaccine", (string)null);
                });

            modelBuilder.Entity("MinuteClinic.Models.Vaccine", b =>
                {
                    b.HasOne("MinuteClinic.Models.Clinics", "Clinic")
                        .WithMany()
                        .HasForeignKey("ClinicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MinuteClinic.Models.Provider", "Providers")
                        .WithMany()
                        .HasForeignKey("ProviderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Clinic");

                    b.Navigation("Providers");
                });
#pragma warning restore 612, 618
        }
    }
}
